### ISSUE TITLE
include binary

### ISSUE THREAD

**Issue by evandrix** [icecr4ck/write-ups#2]
you might want to include the original binary, so that others can follow along and reproduce the results you show in your writeup:

- [keykoolol.zip](https://github.com/icecr4ck/write-ups/files/4646134/keykoolol.zip)
- https://www.virustotal.com/gui/file/422f0908ff251f636d37245fd5b867a753a3fd8ee5f614ef614d54011d407987/details

**Comment by icecr4ck** [comment]
Good point, I added it.
